---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carina-csi-node
  namespace: kube-system
  labels:
    class: carina
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: carina-csi-node-rbac
  labels:
    class: carina
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["*"]
  - apiGroups: ["carina.storage.io"]
    resources: ["logicvolumes", "logicvolumes/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csidrivers"]
    verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: carina-csi-node
  labels:
    class: carina
subjects:
  - kind: ServiceAccount
    name: carina-csi-node
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: carina-csi-node-rbac
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: carina.storage.io
  labels:
    class: carina
spec:
  attachRequired: true
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
#    - Ephemeral