# permissions for end users to view logicvolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logicvolume-viewer-role
rules:
- apiGroups:
  - carina.storage.io
  resources:
  - logicvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - carina.storage.io
  resources:
  - logicvolumes/status
  verbs:
  - get
