
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
- role: worker
  extraMounts:
    - containerPath: /dev
      hostPath: /dev
- role: worker
  extraMounts:
    - containerPath: /dev
      hostPath: /dev
- role: worker
  extraMounts:
    - containerPath: /dev
      hostPath: /dev