---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-carina-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-carina-sc
  volumeMode: Filesystem