---
apiVersion: v1
kind: Pod
metadata:
  name: csi-carina-clone-demo-app
spec:
  containers:
    - name: web-server
      image: docker.io/library/nginx:latest
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www/html
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: carina-pvc-clone
        readOnly: false
