---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carina-pvc-clone
spec:
  storageClassName: csi-carina-sc
  dataSource:
    name: csi-carina-pvc
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
