---
apiVersion: v1
kind: ConfigMap
metadata:
  name: carina-csi-config
  namespace: kube-system
  labels:
    class: carina
data:
  config.json: |-
    {
      "diskSelector": ["loop*", "vd*"],
      "diskScanInterval": "300",
      "diskGroupPolicy": "type",
      "schedulerStrategy": "spradout"
    }
