---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: carina-hook
webhooks:
  - name: pod-hook.carina.storage.io
    namespaceSelector:
      matchExpressions:
      - key: carina.storage.io/webhook
        operator: NotIn
        values: ["ignore"]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EUXhOREEyTkRreE1Wb1hEVE14TURReE1qQTJORGt4TVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT2VtCnVxNU5FR0p4QlNXTnc5aWdsOEwxMmJYVXRvbFhxN1BDZjNiNHpJRDNuMGEvbmNCS0pxbU1yeVVod2huaWNrVEwKbitkeU01ekdtRzhaejhyMmxsdGZNTGY1dWExeG5xakRoS1BoWkxFL2xzRURpT2ZqbTF2eHJyaXpHQk9xNHBjTgp0VmxVZmp6QnhrNzFHQjdsLzI2QkViT2VnMG9UYzlFbUhXYjB0ZFhueDlFQWVScE1jSlI3MS9QU2ttZDdpOGQ5CndVUHdqVHBqMFZoeXZuaEg2OFJ1K3ljOVcwTGNuaEFWb3I4R0FWNUt3NTFtTk1rRGhweDNUS3RuTXBmN3NOcTkKWHhBdm1BRlZYdDFYRkVad202RERuWGpMS1IrY05UVDM1Q2xEbUJ4ZGloRkhFQUV3M0ZIRVF1aG1oNDFvUWw4eQpxeEtUeGk0U1IySzlKa1Q3MEZzQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZGek83OHdsd0hUK3FVOXl5aWROWDZwK2EwOTBNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCYjB6YkhvNG1lMEZYK1FIVVRDTVNKL0xPcE9LWmoydjExN3Q4emVXTlNDb2xCR1dqcQoreHYvWmFIbDl6MlN3WVhhaWdaWEpHditFdTZpbURpcklzb1RlWms0R09uOFR6VXdLRktzclZXMEZic1lQSE9UClp4TGhaTnRWVy93T2FhRUlhSzY1SGFQRUoveUhaeFc5U0VwTjRKRmpxdG1RQUFDeWNiRHRJandZVkwyNjdveHEKQ25TTzFFNDcxamZuSVFLTWZLMllHci8xSzNYRVkwZENGeGlxVHhqSGVPNHF3R1lLQ0FXWFdpOWtTbjJlN0EwNwprZ3FZdi90N3RpWk5ZZ2lQS1BmNjROeGw3N2lySU5nS2NGa0lGM3pNYms0eXZHcllUcE9Jb3VGQkFweFVYN0I0ClVadW8zaFhTdnhNeVV5R1JpSkFLekhvVnFuY2xYblNMbTdxQwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: carina-controller
        namespace: kube-system
        path: /pod/mutate
        port: 443
    failurePolicy: Fail
    matchPolicy: Exact
    objectSelector: {}
    reinvocationPolicy: Never
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1beta1"]
    sideEffects: NoneOnDryRun
    timeoutSeconds: 30